### ISSUE TITLE
January 11, 2022 Meeting Minutes

### ISSUE THREAD

**Issue by kphaterp** [UBC-MDS/textfeatureinfo#1]
- [x] Complete Team Contract
- [x] Pick a topic
- [x] Create project structure
- [x] Summary paragraph to describe project (Lynn)
- [x] bulleted list of functions with small descriptions (everyone)
- [x] paragraph describing how functions fit into python ecosystem (Jacqueline)
- [x] function documentation (everyone)
- Average word lengths (Kiran)
- Get n most frequent words (Jacqueline)
- Get count of punctuation (Lynn)
- Remove stop words (Paniz)
- [x] CONDUCT.md (Paniz)
- [x] CONTRIBUTING.md (Kiran)

**Comment by Jacq4nn** [comment]
I will change my function to "count percentage of fully capitalised words".
